In [1]:
import numpy as np

In [13]:
A = np.random.randint(1,2,(3,3,3))
A

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [14]:
B = np.random.randint(1,5,(3,3))
B

array([[2, 3, 1],
       [1, 3, 1],
       [2, 4, 1]])

In [15]:
A + B

array([[[3, 4, 2],
        [2, 4, 2],
        [3, 5, 2]],

       [[3, 4, 2],
        [2, 4, 2],
        [3, 5, 2]],

       [[3, 4, 2],
        [2, 4, 2],
        [3, 5, 2]]])